/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6_josephmoscoso;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author joseph
 */
public class principalLab extends javax.swing.JFrame {

    /**
     * Creates new form principalLab
     */
    public principalLab() {
        initComponents();
        pred();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jd_registrar = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jt_regc = new javax.swing.JTextField();
        jp_contra = new javax.swing.JPasswordField();
        jdc_fecha = new com.toedter.calendar.JDateChooser();
        jt_tarjeta = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jd_uniflix = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_series = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_pelis = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_favoritos = new javax.swing.JTree();
        jb_agregarf = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jd_admin = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jl_admin1 = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        jl_admin2 = new javax.swing.JList<>();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        menupelis = new javax.swing.JPopupMenu();
        m1_agregar = new javax.swing.JMenuItem();
        m1_modificar = new javax.swing.JMenuItem();
        m1_eliminar = new javax.swing.JMenuItem();
        menuseries = new javax.swing.JPopupMenu();
        Agregar = new javax.swing.JMenuItem();
        Modificar = new javax.swing.JMenuItem();
        Eliminar = new javax.swing.JMenuItem();
        modpelis = new javax.swing.JDialog();
        agpelis = new javax.swing.JDialog();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jt_id = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jt_nombrep = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jt_categoriap = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jt_duracionp = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        ratingp = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jt_productorap = new javax.swing.JTextField();
        jt_directorp = new javax.swing.JTextField();
        jb_agregarp = new javax.swing.JButton();
        modseries = new javax.swing.JDialog();
        agseries = new javax.swing.JDialog();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jt_correo = new javax.swing.JTextField();
        jp_pass = new javax.swing.JPasswordField();
        jb_iniciar = new javax.swing.JButton();
        jb_registrarse = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel5.setText("Por favor, ingrese sus datos correctamente ");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setText("Correo electronico");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setText("Contraseña");

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel8.setText("Fecha de nacimiento");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel9.setText("Tarjeta de credito");

        jButton1.setText("Registrar usuario");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_registrarLayout = new javax.swing.GroupLayout(jd_registrar.getContentPane());
        jd_registrar.getContentPane().setLayout(jd_registrarLayout);
        jd_registrarLayout.setHorizontalGroup(
            jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_registrarLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jt_regc, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                    .addComponent(jp_contra)
                    .addComponent(jdc_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_tarjeta))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_registrarLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_registrarLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_registrarLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(228, 228, 228))))
        );
        jd_registrarLayout.setVerticalGroup(
            jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_registrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(19, 19, 19)
                .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jt_regc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jp_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jdc_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jt_tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel10.setText("Seleccione la pelicula/serie y luego de click al boton para agregar");

        jl_series.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jl_series);

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel11.setText("Series");

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel12.setText("Peliculas");

        jl_pelis.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_pelis);

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel13.setText("Preferidas");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Favoritos");
        jt_favoritos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(jt_favoritos);

        jb_agregarf.setText("------->");
        jb_agregarf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarfMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_uniflixLayout = new javax.swing.GroupLayout(jd_uniflix.getContentPane());
        jd_uniflix.getContentPane().setLayout(jd_uniflixLayout);
        jd_uniflixLayout.setHorizontalGroup(
            jd_uniflixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_uniflixLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jb_agregarf)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_uniflixLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel11)
                .addGap(163, 163, 163)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(77, 77, 77))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_uniflixLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(123, 123, 123))
        );
        jd_uniflixLayout.setVerticalGroup(
            jd_uniflixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_uniflixLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jd_uniflixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGroup(jd_uniflixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_uniflixLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_uniflixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)))
                    .addGroup(jd_uniflixLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jb_agregarf)))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        jLabel14.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel14.setText("Administrador");

        jLabel15.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel15.setText("Peliculas");

        jLabel16.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel16.setText("Series");

        jl_admin1.setModel(new DefaultListModel());
        jl_admin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_admin1MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jl_admin1);

        jl_admin2.setModel(new DefaultListModel());
        jl_admin2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_admin2MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jl_admin2);

        jLabel17.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel17.setText("Haga click derecho dentro de cualquier lista para ver opciones");

        javax.swing.GroupLayout jd_adminLayout = new javax.swing.GroupLayout(jd_admin.getContentPane());
        jd_admin.getContentPane().setLayout(jd_adminLayout);
        jd_adminLayout.setHorizontalGroup(
            jd_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_adminLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(jd_adminLayout.createSequentialGroup()
                .addGroup(jd_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_adminLayout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel14))
                    .addGroup(jd_adminLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel17)))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(jd_adminLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(124, 124, 124))
        );
        jd_adminLayout.setVerticalGroup(
            jd_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_adminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addGap(26, 26, 26)
                .addGroup(jd_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane5.setViewportView(jTextArea2);

        m1_agregar.setText("Agregar");
        m1_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m1_agregarActionPerformed(evt);
            }
        });
        menupelis.add(m1_agregar);

        m1_modificar.setText("Modificar");
        m1_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m1_modificarActionPerformed(evt);
            }
        });
        menupelis.add(m1_modificar);

        m1_eliminar.setText("Eliminar");
        menupelis.add(m1_eliminar);

        Agregar.setText("Agregar");
        menuseries.add(Agregar);

        Modificar.setText("Modificar");
        menuseries.add(Modificar);

        Eliminar.setText("Eliminar");
        menuseries.add(Eliminar);

        javax.swing.GroupLayout modpelisLayout = new javax.swing.GroupLayout(modpelis.getContentPane());
        modpelis.getContentPane().setLayout(modpelisLayout);
        modpelisLayout.setHorizontalGroup(
            modpelisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        modpelisLayout.setVerticalGroup(
            modpelisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel18.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel18.setText("Agregar");

        jLabel19.setText("Id");

        jLabel20.setText("Nombre");

        jLabel21.setText("Categoria");

        jLabel22.setText("Duracion");

        jLabel23.setText("Rating");

        jLabel24.setText("Productora");

        jLabel25.setText("Director");

        jb_agregarp.setText("Agregar");
        jb_agregarp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarpMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout agpelisLayout = new javax.swing.GroupLayout(agpelis.getContentPane());
        agpelis.getContentPane().setLayout(agpelisLayout);
        agpelisLayout.setHorizontalGroup(
            agpelisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agpelisLayout.createSequentialGroup()
                .addGroup(agpelisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agpelisLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabel18))
                    .addGroup(agpelisLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(agpelisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(agpelisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jt_nombrep, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                            .addComponent(jt_categoriap)
                            .addComponent(jt_duracionp, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ratingp, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(agpelisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jt_directorp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                .addComponent(jt_productorap, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(agpelisLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jb_agregarp)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        agpelisLayout.setVerticalGroup(
            agpelisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agpelisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(agpelisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(agpelisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jt_nombrep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(agpelisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jt_categoriap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(agpelisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jt_duracionp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(agpelisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(ratingp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(agpelisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jt_productorap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(agpelisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jt_directorp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jb_agregarp)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout modseriesLayout = new javax.swing.GroupLayout(modseries.getContentPane());
        modseries.getContentPane().setLayout(modseriesLayout);
        modseriesLayout.setHorizontalGroup(
            modseriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        modseriesLayout.setVerticalGroup(
            modseriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout agseriesLayout = new javax.swing.GroupLayout(agseries.getContentPane());
        agseries.getContentPane().setLayout(agseriesLayout);
        agseriesLayout.setHorizontalGroup(
            agseriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        agseriesLayout.setVerticalGroup(
            agseriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane8.setViewportView(jTextArea3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("Uniflix");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel2.setText("Por favor ingrese sus datos para iniciar sesion");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Correo electronico");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setText("Contraseña");

        jb_iniciar.setText("Iniciar Sesion");
        jb_iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_iniciarMouseClicked(evt);
            }
        });

        jb_registrarse.setText("Registrarse");
        jb_registrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_registrarseMouseClicked(evt);
            }
        });

        jButton2.setText("Ayuda (administrador)");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(265, 265, 265))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jp_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jb_iniciar)
                        .addGap(53, 53, 53)
                        .addComponent(jButton2)
                        .addGap(46, 46, 46)
                        .addComponent(jb_registrarse)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jp_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_iniciar)
                    .addComponent(jb_registrarse)
                    .addComponent(jButton2))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_iniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_iniciarMouseClicked
        // TODO add your handling code here:
        String correo = jt_correo.getText();
        String contra = jp_pass.getText();
        try {
            for (Usuarios u : usuario) {
                if (correo.equals(u.getCorreo()) && contra.equals(u.getContraseña())) {
                    DefaultListModel m = (DefaultListModel) jl_pelis.getModel();;
                    DefaultListModel x = (DefaultListModel) jl_series.getModel();;
                    for (int i = 0; i < pelicula.size(); i++) {
                        m.addElement(pelicula.get(i));
                        jl_pelis.setModel(m);
                    }
                    for (int i = 0; i < serie.size(); i++) {
                        x.addElement(serie.get(i));
                        jl_series.setModel(x);
                    }
//                    jl_pelis.setModel(m);
//                    jl_series.setModel(x);
                    jd_uniflix.setModal(true);
                    jd_uniflix.pack();
                    jd_uniflix.setLocationRelativeTo(this);
                    jd_uniflix.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Error, correo o contraseña incorrectos");
                }
            }
            if (correo.equals(usuarioa) && contra.equals(contraa)) {
                DefaultListModel m = (DefaultListModel) jl_admin1.getModel();;
                DefaultListModel x = (DefaultListModel) jl_admin2.getModel();;
                for (int i = 0; i < pelicula.size(); i++) {
                    m.addElement(pelicula.get(i));
                    jl_admin1.setModel(m);
                }
                for (int i = 0; i < serie.size(); i++) {
                    x.addElement(serie.get(i));
                    jl_admin2.setModel(x);
                }
//                    jl_pelis.setModel(m);
//                    jl_series.setModel(x);
                jd_admin.setModal(true);
                jd_admin.pack();
                jd_admin.setLocationRelativeTo(this);
                jd_admin.setVisible(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error, datos incorrectos");
        }
    }//GEN-LAST:event_jb_iniciarMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        try {
            String correo = jt_regc.getText();
            String contra = jp_contra.getText();
            String date = jdc_fecha.getDate().toString();
            String tarjeta = jt_tarjeta.getText();
            usuario.add(new Usuarios(correo, contra, date, tarjeta));
            JOptionPane.showMessageDialog(jd_registrar, "Usuario registrado con exito");
            jd_registrar.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jd_registrar, "Error al registrar usuario, verifique sus datos");
        }

    }//GEN-LAST:event_jButton1MouseClicked
    public void pred() {
        pelicula.add(new peliculas("22", "Logan", "Accion", "1:40", 5, "Fox", "Fox"));
        pelicula.get(0).getIdiomas().add("Español");
        pelicula.get(0).getIdiomas().add("Ingles");
        pelicula.get(0).getIdiomas().add("Aleman");
        pelicula.get(0).getSubtitulos().add("Español");
        pelicula.get(0).getSubtitulos().add("Ingles");
        pelicula.get(0).getSubtitulos().add("Aleman");
        pelicula.get(0).getComentarios().add("Bastante emotiva");
        pelicula.get(0).getActores().add("Hugh Jackman");
        pelicula.add(new peliculas("33", "Clockwork Orange", "Accion/drama", "2:40", 4, "Warner", "Cubrick"));
        pelicula.get(1).getIdiomas().add("Español");
        pelicula.get(1).getIdiomas().add("Ingles");
        pelicula.get(1).getIdiomas().add("Aleman");
        pelicula.get(1).getIdiomas().add("Español");
        pelicula.get(1).getIdiomas().add("Ingles");
        pelicula.get(1).getIdiomas().add("Aleman");
        pelicula.get(1).getSubtitulos().add("Español");
        pelicula.get(1).getSubtitulos().add("Ingles");
        pelicula.get(1).getSubtitulos().add("Aleman");
        pelicula.get(1).getComentarios().add("Turbia a veces pero disfrutable");
        pelicula.get(1).getActores().add("Desconocido");
        pelicula.add(new peliculas("52", "Kill Bill", "Accion", "1:40", 4, "Warner", "Tarantino"));
        pelicula.get(2).getIdiomas().add("Español");
        pelicula.get(2).getIdiomas().add("Ingles");
        pelicula.get(2).getIdiomas().add("Aleman");
        pelicula.get(2).getIdiomas().add("Español");
        pelicula.get(2).getIdiomas().add("Ingles");
        pelicula.get(2).getIdiomas().add("Aleman");
        pelicula.get(2).getSubtitulos().add("Español");
        pelicula.get(2).getSubtitulos().add("Ingles");
        pelicula.get(2).getSubtitulos().add("Aleman");
        pelicula.get(2).getComentarios().add("Buena pelicula de accion");
        pelicula.get(2).getActores().add("Desconocido");
        pelicula.add(new peliculas("62", "Watchmen", "Accion/drama", "2:40", 4, "Fox", "Snyder"));
        pelicula.get(3).getIdiomas().add("Español");
        pelicula.get(3).getIdiomas().add("Ingles");
        pelicula.get(3).getIdiomas().add("Aleman");
        pelicula.get(3).getIdiomas().add("Español");
        pelicula.get(3).getIdiomas().add("Ingles");
        pelicula.get(3).getIdiomas().add("Aleman");
        pelicula.get(3).getSubtitulos().add("Español");
        pelicula.get(3).getSubtitulos().add("Ingles");
        pelicula.get(3).getSubtitulos().add("Aleman");
        pelicula.get(3).getComentarios().add("Buena adaptacion al cine de un comic");
        pelicula.get(3).getActores().add("Desconocido");
        pelicula.add(new peliculas("12", "Ella", "Drama", "1:40", 3, "Canada Studios", "Desconocido"));
        pelicula.get(4).getIdiomas().add("Español");
        pelicula.get(4).getIdiomas().add("Ingles");
        pelicula.get(4).getIdiomas().add("Aleman");
        pelicula.get(4).getIdiomas().add("Español");
        pelicula.get(4).getIdiomas().add("Ingles");
        pelicula.get(4).getIdiomas().add("Aleman");
        pelicula.get(4).getSubtitulos().add("Español");
        pelicula.get(4).getSubtitulos().add("Ingles");
        pelicula.get(4).getSubtitulos().add("Aleman");
        pelicula.get(4).getComentarios().add("Aburre");
        pelicula.get(4).getActores().add("Desconocida");
        pelicula.add(new peliculas("2122", "The Simpson", "Comedia", "1:20", 2, "Fox", "Matt Groening"));
        pelicula.get(5).getIdiomas().add("Español");
        pelicula.get(5).getIdiomas().add("Ingles");
        pelicula.get(5).getIdiomas().add("Aleman");
        pelicula.get(5).getIdiomas().add("Español");
        pelicula.get(5).getIdiomas().add("Ingles");
        pelicula.get(5).getIdiomas().add("Aleman");
        pelicula.get(5).getSubtitulos().add("Español");
        pelicula.get(5).getSubtitulos().add("Ingles");
        pelicula.get(5).getSubtitulos().add("Aleman");
        pelicula.get(5).getComentarios().add("Bastante mala como comedia pero se disfruta");
        pelicula.get(5).getActores().add("Desconocido");
        pelicula.add(new peliculas("3333", "The end of evangelion", "Accion/Psicologico", "1:40", 5, "Desconocido", "Hideaki Anno"));
        pelicula.get(6).getIdiomas().add("Español");
        pelicula.get(6).getIdiomas().add("Ingles");
        pelicula.get(6).getIdiomas().add("Aleman");
        pelicula.get(6).getIdiomas().add("Español");
        pelicula.get(6).getIdiomas().add("Ingles");
        pelicula.get(6).getIdiomas().add("Aleman");
        pelicula.get(6).getSubtitulos().add("Español");
        pelicula.get(6).getSubtitulos().add("Ingles");
        pelicula.get(6).getSubtitulos().add("Aleman");
        pelicula.get(6).getComentarios().add("Turbia con mensaje existencial");
        pelicula.get(6).getActores().add("Desconocido");
        pelicula.add(new peliculas("ewq", "Pacific Rim", "Accion", "1:50", 5, "Fox", "Guillermo del Toro"));
        pelicula.get(7).getIdiomas().add("Español");
        pelicula.get(7).getIdiomas().add("Ingles");
        pelicula.get(7).getIdiomas().add("Aleman");
        pelicula.get(7).getIdiomas().add("Español");
        pelicula.get(7).getIdiomas().add("Ingles");
        pelicula.get(7).getIdiomas().add("Aleman");
        pelicula.get(7).getSubtitulos().add("Español");
        pelicula.get(7).getSubtitulos().add("Ingles");
        pelicula.get(7).getSubtitulos().add("Aleman");
        pelicula.get(7).getComentarios().add("Se parece a evangelion");
        pelicula.get(7).getActores().add("Desconocido");
        pelicula.add(new peliculas("eee", "Your Name", "Drama/comedia", "1:30", 4, "Desconocida", "Desconocida"));
        pelicula.get(8).getIdiomas().add("Español");
        pelicula.get(8).getIdiomas().add("Ingles");
        pelicula.get(8).getIdiomas().add("Aleman");
        pelicula.get(8).getIdiomas().add("Español");
        pelicula.get(8).getIdiomas().add("Ingles");
        pelicula.get(8).getIdiomas().add("Aleman");
        pelicula.get(8).getSubtitulos().add("Español");
        pelicula.get(8).getSubtitulos().add("Ingles");
        pelicula.get(8).getSubtitulos().add("Aleman");
        pelicula.get(8).getComentarios().add("buen");
        pelicula.get(8).getActores().add("Desconocida");
        pelicula.add(new peliculas("x", "Die Hard", "Accion", "1:40", 1, "?", "?"));
        pelicula.get(9).getIdiomas().add("Español");
        pelicula.get(9).getIdiomas().add("Ingles");
        pelicula.get(9).getIdiomas().add("Aleman");
        pelicula.get(9).getIdiomas().add("Español");
        pelicula.get(9).getIdiomas().add("Ingles");
        pelicula.get(9).getIdiomas().add("Aleman");
        pelicula.get(9).getSubtitulos().add("Español");
        pelicula.get(9).getSubtitulos().add("Ingles");
        pelicula.get(9).getSubtitulos().add("Aleman");
        pelicula.get(9).getComentarios().add("Accion del monton");
        pelicula.get(9).getActores().add("Bruce Willis");
        serie.add(new series("323232", "Breaking Bad", 5, "Accion", "50", 5, "Desconocido", "Desconocido"));
        serie.get(0).getIdiomas().add("Español");
        serie.get(0).getIdiomas().add("Ingles");
        serie.get(0).getIdiomas().add("Aleman");
        serie.get(0).getSubtitulos().add("Español");
        serie.get(0).getSubtitulos().add("Ingles");
        serie.get(0).getSubtitulos().add("Aleman");
        serie.get(0).getComentarios().add("Buen desarrollo de personajes");
        serie.get(0).getActores().add("Walter");
        serie.add(new series("xxxxxx", "House of Cards", 5, "Seinen", "50", 5, "Desconocido", "Desconocido"));
        serie.get(1).getIdiomas().add("Español");
        serie.get(1).getIdiomas().add("Ingles");
        serie.get(1).getIdiomas().add("Aleman");
        serie.get(1).getSubtitulos().add("Español");
        serie.get(1).getSubtitulos().add("Ingles");
        serie.get(1).getSubtitulos().add("Aleman");
        serie.get(1).getComentarios().add("Buen desarrollo de personajes");
        serie.get(1).getActores().add("Kevin Spacey");
        serie.add(new series("cccccc", "Devilman Crybaby", 5, "Accion", "50", 5, "Desconocido", "Desconocido"));
        serie.get(2).getIdiomas().add("Español");
        serie.get(2).getIdiomas().add("Ingles");
        serie.get(2).getIdiomas().add("Aleman");
        serie.get(2).getSubtitulos().add("Español");
        serie.get(2).getSubtitulos().add("Ingles");
        serie.get(2).getSubtitulos().add("Aleman");
        serie.get(2).getComentarios().add("Buen desarrollo de personajes y buen gore a veces");
        serie.get(2).getActores().add("Desconocido");
        serie.add(new series("vvvvvv", "Neon Genesis Evangelion", 5, "Accion/psicologico", "30", 5, "Desconocido", "Hideaki Anno"));
        serie.get(3).getIdiomas().add("Español");
        serie.get(3).getIdiomas().add("Ingles");
        serie.get(3).getIdiomas().add("Aleman");
        serie.get(3).getSubtitulos().add("Español");
        serie.get(3).getSubtitulos().add("Ingles");
        serie.get(3).getSubtitulos().add("Aleman");
        serie.get(3).getComentarios().add("Buen desarrollo de personajes");
        serie.get(3).getActores().add("Desconocido");
        serie.add(new series("vvvvvv", "this", 5, "Accion", "50", 5, "Desconocido", "Desconocido"));
        serie.get(4).getIdiomas().add("Español");
        serie.get(4).getIdiomas().add("Ingles");
        serie.get(4).getIdiomas().add("Aleman");
        serie.get(4).getSubtitulos().add("Español");
        serie.get(4).getSubtitulos().add("Ingles");
        serie.get(4).getSubtitulos().add("Aleman");
        serie.get(4).getComentarios().add("Buen desarrollo de personajes");
        serie.get(4).getActores().add("Walter");
        serie.add(new series("zzzzzz", "x", 5, "Accion", "50", 5, "Desconocido", "Desconocido"));
        serie.get(5).getIdiomas().add("Español");
        serie.get(5).getIdiomas().add("Ingles");
        serie.get(5).getIdiomas().add("Aleman");
        serie.get(5).getSubtitulos().add("Español");
        serie.get(5).getSubtitulos().add("Ingles");
        serie.get(5).getSubtitulos().add("Aleman");
        serie.get(5).getComentarios().add("Buen desarrollo de personajes");
        serie.get(5).getActores().add("Walter");
        serie.add(new series("3ssss", "Hannibal", 5, "Accion", "50", 5, "Desconocido", "Desconocido"));
        serie.get(6).getIdiomas().add("Español");
        serie.get(6).getIdiomas().add("Ingles");
        serie.get(6).getIdiomas().add("Aleman");
        serie.get(6).getSubtitulos().add("Español");
        serie.get(6).getSubtitulos().add("Ingles");
        serie.get(6).getSubtitulos().add("Aleman");
        serie.get(6).getComentarios().add("Buen desarrollo de personajes");
        serie.get(6).getActores().add("Walter");
        serie.add(new series("ggggg", "k", 5, "Accion", "50", 5, "Desconocido", "Desconocido"));
        serie.get(7).getIdiomas().add("Español");
        serie.get(7).getIdiomas().add("Ingles");
        serie.get(7).getIdiomas().add("Aleman");
        serie.get(7).getSubtitulos().add("Español");
        serie.get(7).getSubtitulos().add("Ingles");
        serie.get(7).getSubtitulos().add("Aleman");
        serie.get(7).getComentarios().add("Buen desarrollo de personajes");
        serie.get(7).getActores().add("Walter");
        serie.add(new series("wwwww", "w", 5, "Accion", "50", 5, "Desconocido", "Desconocido"));
        serie.get(8).getIdiomas().add("Español");
        serie.get(8).getIdiomas().add("Ingles");
        serie.get(8).getIdiomas().add("Aleman");
        serie.get(8).getSubtitulos().add("Español");
        serie.get(8).getSubtitulos().add("Ingles");
        serie.get(8).getSubtitulos().add("Aleman");
        serie.get(8).getComentarios().add("Buen desarrollo de personajes");
        serie.get(8).getActores().add("Walter");
        serie.add(new series("yyyyyy", "y", 5, "Accion", "50", 5, "Desconocido", "Desconocido"));
        serie.get(9).getIdiomas().add("Español");
        serie.get(9).getIdiomas().add("Ingles");
        serie.get(9).getIdiomas().add("Aleman");
        serie.get(9).getSubtitulos().add("Español");
        serie.get(9).getSubtitulos().add("Ingles");
        serie.get(9).getSubtitulos().add("Aleman");
        serie.get(9).getComentarios().add("Buen desarrollo de personajes");
        serie.get(9).getActores().add("Walter");
    }
    private void jb_registrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_registrarseMouseClicked
        // TODO add your handling code here:
        jd_registrar.setModal(true);
        jd_registrar.pack();
        jd_registrar.setLocationRelativeTo(this);
        jd_registrar.setVisible(true);
    }//GEN-LAST:event_jb_registrarseMouseClicked

    private void jb_agregarfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarfMouseClicked
        // TODO add your handling code here:
        String correo = jt_correo.getText();
        String contra = jp_pass.getText();
        textos te = new textos("./Usuarios.txt");
        try {
            if (jl_pelis.getSelectedIndex() >= 0) {
                DefaultTreeModel m = (DefaultTreeModel) jt_favoritos.getModel();
                DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
                DefaultListModel model = (DefaultListModel) jl_pelis.getModel();
                DefaultMutableTreeNode cat, cat2;
                String categoria;
                String nombre, id, duracion, productora, director;
                int rating;
                ArrayList idiomas = new ArrayList();
                ArrayList subtitulos = new ArrayList();
                ArrayList comentarios = new ArrayList();
                ArrayList actores = new ArrayList();
                id = ((peliculas) model.get(jl_pelis.getSelectedIndex())).getId();
                categoria = ((peliculas) model.get(jl_pelis.getSelectedIndex())).getCategoria();
                nombre = ((peliculas) model.get(jl_pelis.getSelectedIndex())).getNombre();
                duracion = ((peliculas) model.get(jl_pelis.getSelectedIndex())).getDuracion();
                productora = ((peliculas) model.get(jl_pelis.getSelectedIndex())).getProductora();
                rating = ((peliculas) model.get(jl_pelis.getSelectedIndex())).getRating();
                director = ((peliculas) model.get(jl_pelis.getSelectedIndex())).getDirector();
                idiomas.add(((peliculas) model.get(jl_pelis.getSelectedIndex())).getActores());
                subtitulos.add(((peliculas) model.get(jl_pelis.getSelectedIndex())).getSubtitulos());
                comentarios.add(((peliculas) model.get(jl_pelis.getSelectedIndex())).getComentarios());
                actores.add(((peliculas) model.get(jl_pelis.getSelectedIndex())).getActores());
                cat = new DefaultMutableTreeNode(categoria);
                cat2 = new DefaultMutableTreeNode("Pelicula");
                for (Usuarios u : usuario) {
                    if (correo.equals(u.getCorreo()) && contra.equals(u.getContraseña())) {
                        u.getPelis().add(new peliculas(id, nombre, categoria, duracion, rating, productora, director));
                        u.getPelis().get(u.getPelis().size() - 1).getActores().add(actores);
                        u.getPelis().get(u.getPelis().size() - 1).getIdiomas().add(idiomas);
                        u.getPelis().get(u.getPelis().size() - 1).getComentarios().add(comentarios);
                        u.getPelis().get(u.getPelis().size() - 1).getSubtitulos().add(subtitulos);
                    }
                }
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(new peliculas(id, nombre, categoria, duracion, rating, productora, director));
                cat.add(p);
                cat2.add(cat);
                raiz.add(cat2);
                c2++;
                m.reload();
            }
            if (jl_series.getSelectedIndex() >= 0) {
                DefaultTreeModel m = (DefaultTreeModel) jt_favoritos.getModel();
                DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
                DefaultListModel model = (DefaultListModel) jl_series.getModel();
                DefaultMutableTreeNode cat, cat2;
                String categoria;
                String nombre, id, duracion, productora, director;
                int rating, temporadas;
                ArrayList idiomas = new ArrayList();
                ArrayList subtitulos = new ArrayList();
                ArrayList comentarios = new ArrayList();
                ArrayList actores = new ArrayList();
                id = ((series) model.get(jl_series.getSelectedIndex())).getId();
                categoria = ((series) model.get(jl_series.getSelectedIndex())).getCategoria();
                nombre = ((series) model.get(jl_series.getSelectedIndex())).getNombre();
                duracion = ((series) model.get(jl_series.getSelectedIndex())).getDuracion();
                productora = ((series) model.get(jl_series.getSelectedIndex())).getProductora();
                rating = ((series) model.get(jl_series.getSelectedIndex())).getRating();
                temporadas = ((series) model.get(jl_series.getSelectedIndex())).getTemporadas();
                director = ((series) model.get(jl_series.getSelectedIndex())).getDirector();
                idiomas.add(((series) model.get(jl_series.getSelectedIndex())).getIdiomas());
                subtitulos.add(((series) model.get(jl_series.getSelectedIndex())).getSubtitulos());
                comentarios.add(((series) model.get(jl_series.getSelectedIndex())).getComentarios());
                actores.add(((series) model.get(jl_series.getSelectedIndex())).getActores());
                cat = new DefaultMutableTreeNode(categoria);
                cat2 = new DefaultMutableTreeNode("Serie");
                for (Usuarios u : usuario) {
                    if (correo.equals(u.getCorreo()) && contra.equals(u.getContraseña())) {
                        u.getSerie().add(new series(id, nombre, temporadas, categoria, duracion, rating, productora, director));
                        u.getSerie().get(u.getSerie().size() - 1).getActores().add(actores);
                        u.getSerie().get(u.getSerie().size() - 1).getIdiomas().add(idiomas);
                        u.getSerie().get(u.getSerie().size() - 1).getComentarios().add(comentarios);
                        u.getSerie().get(u.getSerie().size() - 1).getSubtitulos().add(subtitulos);
                    }
                }
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(new series(id, nombre, temporadas, categoria, duracion, rating, productora, director));
                cat.add(p);
                cat2.add(cat);
                raiz.add(cat2);
                c++;
                m.reload();
            }
            for (Usuarios u : usuario) {
                if (correo.equals(u.getCorreo()) && contra.equals(u.getContraseña())) {
                    File archivo = null;
                    FileWriter fw = null;
                    BufferedWriter bw = null;
                    try {
                        archivo = new File("./Usuarios.txt");
                        fw = new FileWriter(archivo, true);
                        bw = new BufferedWriter(fw);
                        // bw.newLine();
                        bw.write(u.toString() + ";");
                        bw.newLine();
                        bw.flush();
                    } catch (Exception e) {
                    }
                    bw.close();
                    fw.close();
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(jd_uniflix, "Error fatal");
        }
    }//GEN-LAST:event_jb_agregarfMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Correo=Admin\nContraseña=Admin");
    }//GEN-LAST:event_jButton2MouseClicked

    private void jl_admin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_admin1MouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            if (jl_admin1.getSelectedIndex() >= 0) {
                menupelis.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jl_admin1MouseClicked

    private void jl_admin2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_admin2MouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            if (jl_admin2.getSelectedIndex() >= 0) {
                menuseries.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jl_admin2MouseClicked

    private void m1_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m1_agregarActionPerformed
        // TODO add your handling code here:
        agpelis.setModal(true);
        agpelis.pack();
        agpelis.setLocationRelativeTo(this);
        agpelis.setVisible(true);
    }//GEN-LAST:event_m1_agregarActionPerformed

    private void m1_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m1_modificarActionPerformed
        // TODO add your handling code here:
        modpelis.setModal(true);
        modpelis.pack();
        modpelis.setLocationRelativeTo(this);
        modpelis.setVisible(true);
    }//GEN-LAST:event_m1_modificarActionPerformed

    private void jb_agregarpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarpMouseClicked
        // TODO add your handling code here:
        String id=jt_id.getText();
        String nombre=jt_nombrep.getText();
        String categoria=jt_categoriap.getText();
        String duracion=jt_duracionp.getText();
        int rating=Integer.parseInt(ratingp.getText());
        String productora=jt_productorap.getText();
        String director=jt_directorp.getText();
        pelicula.add(new peliculas(id, nombre, categoria, duracion, rating, productora, director));
    }//GEN-LAST:event_jb_agregarpMouseClicked

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principalLab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principalLab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principalLab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principalLab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principalLab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Agregar;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JDialog agpelis;
    private javax.swing.JDialog agseries;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JButton jb_agregarf;
    private javax.swing.JButton jb_agregarp;
    private javax.swing.JButton jb_iniciar;
    private javax.swing.JButton jb_registrarse;
    private javax.swing.JDialog jd_admin;
    private javax.swing.JDialog jd_registrar;
    private javax.swing.JDialog jd_uniflix;
    private com.toedter.calendar.JDateChooser jdc_fecha;
    private javax.swing.JList<String> jl_admin1;
    private javax.swing.JList<String> jl_admin2;
    private javax.swing.JList<String> jl_pelis;
    private javax.swing.JList<String> jl_series;
    private javax.swing.JPasswordField jp_contra;
    private javax.swing.JPasswordField jp_pass;
    private javax.swing.JTextField jt_categoriap;
    private javax.swing.JTextField jt_correo;
    private javax.swing.JTextField jt_directorp;
    private javax.swing.JTextField jt_duracionp;
    private javax.swing.JTree jt_favoritos;
    private javax.swing.JTextField jt_id;
    private javax.swing.JTextField jt_nombrep;
    private javax.swing.JTextField jt_productorap;
    private javax.swing.JTextField jt_regc;
    private javax.swing.JTextField jt_tarjeta;
    private javax.swing.JMenuItem m1_agregar;
    private javax.swing.JMenuItem m1_eliminar;
    private javax.swing.JMenuItem m1_modificar;
    private javax.swing.JPopupMenu menupelis;
    private javax.swing.JPopupMenu menuseries;
    private javax.swing.JDialog modpelis;
    private javax.swing.JDialog modseries;
    private javax.swing.JTextField ratingp;
    // End of variables declaration//GEN-END:variables
    String usuarioa = "Admin";
    String contraa = "Admin";
    ArrayList<Usuarios> usuario = new ArrayList();
    ArrayList<peliculas> pelicula = new ArrayList();
    ArrayList<series> serie = new ArrayList();
    int c = 0;
    int c2 = 0;
}
